from __future__ import annotations

import shutil
import stat
from importlib import resources
from pathlib import Path

ICON_FILENAME = "panda-switcher.png"
PERSONAL_ICON_FILENAME = "panda-switcher-personal.png"
STATUS_SCRIPT_FILENAME = "granola-switcher-status.sh"

SCRIPT_TEMPLATE = """#!/bin/bash
# Generated by `granola-switcher raycast-install`. Re-run that command to regenerate.
# @raycast.schemaVersion 1
# @raycast.title {title}
# @raycast.mode compact
# @raycast.packageName Granola Switcher
# @raycast.icon {icon}

set -euo pipefail

# Raycast runs scripts with a minimal PATH, so resolve the CLI explicitly.
GS="$(command -v granola-switcher || true)"
if [ -z "$GS" ]; then
  for candidate in /opt/homebrew/bin/granola-switcher /usr/local/bin/granola-switcher; do
    if [ -x "$candidate" ]; then
      GS="$candidate"
      break
    fi
  done
fi
if [ -z "$GS" ]; then
  echo "granola-switcher not found. Install it: brew install yanda/tap/granola-switcher" >&2
  exit 1
fi

exec "$GS" {arguments}
"""


def render_script(*, title: str, arguments: str, icon: str = ICON_FILENAME) -> str:
    return SCRIPT_TEMPLATE.format(title=title, icon=icon, arguments=arguments)


def write_script(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_scripts(target: Path, profiles: list[tuple[str, str]]) -> list[Path]:
    """Write Raycast script commands for each (name, title) profile plus status and icons."""
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for name, title in profiles:
        path = target / f"switch-granola-{name}.sh"
        icon = PERSONAL_ICON_FILENAME if name == "personal" else ICON_FILENAME
        write_script(path, render_script(title=f"Granola: {title}", arguments=f"switch {name}", icon=icon))
        written.append(path)

    status_path = target / STATUS_SCRIPT_FILENAME
    write_script(status_path, render_script(title="Granola: Selected Account", arguments="selected"))
    written.append(status_path)

    for icon_filename in (ICON_FILENAME, PERSONAL_ICON_FILENAME):
        icon_source = resources.files("granola_switcher") / "data" / icon_filename
        icon_target = target / icon_filename
        with resources.as_file(icon_source) as icon_path:
            shutil.copyfile(icon_path, icon_target)
        written.append(icon_target)

    return written
